version: 3.0.36.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
environment:
  VCDIR: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib32-msvc-12.0
  BOOST_INCLUDEDIR: C:\Libraries\boost
install:
- cmd: >-
    appveyor DownloadFile http://zlib.net/zlib-1.2.8.tar.gz -FileName zlib-1.2.8.tar.gz

    7z x zlib-1.2.8.tar.gz > NUL

    7z x zlib-1.2.8.tar > NUL

    cd zlib-1.2.8

    md build

    cd build

    cmake ..

    cmake --build . --config Release

    copy zconf.h ..

    cd ..

    cd ..
build_script:
- cmd: >-
    "%VCDIR%"\vcvarsall.bat

    cmake -G "Visual Studio 12" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%\zlib-1.2.8\build\Release\zlib.lib -DZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\zlib-1.2.8 .

    cmake --build . --config Release
artifacts:
- path: Release\*.exe
  name: v8unpack
deploy: off